/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelItem;

import com.API.Message;
import com.API.admin;
import com.DAO.ChiTietBanHangDAO;
import com.DAO.HangHoaDAO;
import com.DAO.HoaDonBanHangDAO;
import com.DAO.LoaiHangDAO;
import com.DAO.PhieuBanHangDAO;
import com.SUPPORT.BanHangSP;
import com.entity.ChiTietBanHang;
import com.entity.HangHoa;
import com.entity.HoaDonBanHang;
import com.entity.LoaiHang;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javacafe.DangNhapDialog;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
//xongggggggggggggggggggggg

/**
 *
 * @author lamqw
 */
public class BanHangJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BanHangJPanel
     */
    public BanHangJPanel() {
        initComponents();
        init();
    }
    String mahhdh;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTenHh = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThanhTien = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        btnHuy = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHangHoa = new javax.swing.JTable();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cboLoaiHang = new javax.swing.JComboBox<>();
        btnThanhToan = new javax.swing.JButton();

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(77, 166, 255));
        jLabel1.setText("Bán Hàng");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(77, 166, 255), null), "ORDER ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel5.setText("Tên hàng hoa:");

        jLabel6.setText("Đơn giá:");

        txtTenHh.setEditable(false);

        txtDonGia.setEditable(false);
        txtDonGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonGiaActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(255, 102, 102));
        btnUpdate.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Cập nhật");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        tblThanhTien.setBackground(new java.awt.Color(77, 166, 255));
        tblThanhTien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên hàng", "Số lượng", "Thành Tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblThanhTien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThanhTienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblThanhTien);

        jLabel8.setText("Số Lượng :");

        btnHuy.setBackground(new java.awt.Color(255, 102, 102));
        btnHuy.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Huỷ món");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSoLuong)
                    .addComponent(txtTenHh, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdate)
                    .addComponent(btnHuy))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTenHh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnHuy)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnUpdate)))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(77, 166, 255), null), "Thực đơn ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tblHangHoa.setBackground(new java.awt.Color(77, 166, 255));
        tblHangHoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên hàng hoá", "Đơn giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHangHoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHangHoaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblHangHoa);

        btnTimKiem.setBackground(new java.awt.Color(77, 166, 255));
        btnTimKiem.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jLabel7.setText("Loại hàng:");

        cboLoaiHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLoaiHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTimKiem)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTimKiem)
                    .addComponent(cboLoaiHang, 0, 213, Short.MAX_VALUE))
                .addGap(16, 16, 16))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboLoaiHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );

        btnThanhToan.setBackground(new java.awt.Color(0, 255, 0));
        btnThanhToan.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btnThanhToan.setText("Thanh toán");
        btnThanhToan.setActionCommand("");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(363, 363, 363)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnThanhToan)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(79, 79, 79)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThanhToan)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        thanhToan();        // TODO add your handling code here:
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        timkiem();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        huy();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        updateHd();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblHangHoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHangHoaMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            chonHangHoa();
        }
    }//GEN-LAST:event_tblHangHoaMouseClicked

    private void tblThanhTienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThanhTienMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            getHangHoaFormTable();
        }
    }//GEN-LAST:event_tblThanhTienMouseClicked

    private void cboLoaiHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiHangActionPerformed
        // TODO add your handling code here:
        fillTableHangHoa();
    }//GEN-LAST:event_cboLoaiHangActionPerformed

    private void txtDonGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonGiaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboLoaiHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblHangHoa;
    private javax.swing.JTable tblThanhTien;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenHh;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
  String Mahhbh = "";

    void getHangHoaFormTable() {
        String ten = (String) tblThanhTien.getValueAt(tblThanhTien.getSelectedRow(), 0);
        HangHoa hh = hhdao.selectHHByName(ten);
        ChiTietBanHang ctbh = ctbhdao.SelectByhh(BanHangSP.getMaHoaDonBanHang(), hh.getMahh());
        setForm(ctbh);
    }

    public void init() {
        fillComboBoxLoaiHang();
        try {
            if (!BanHangSP.CheckMaBanHang()) {
                BanHangSP.setMaHoaDonBanHang(pbhdao.getMaPhieubanHangNeẉ̣());
                HoaDonBanHang hhbh = new HoaDonBanHang();
                hhbh.setMakh("kh1");
                hhbh.setNgayhdbh(LocalDateTime.now());
                hhbh.setManv(admin.user.getManv());
                hdbhdao.insert(hhbh);
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        fillTableThanhToan();
    }

    void huy() {
        if (Message.confirm(this, "Bạn muốn xóa  \"" + txtTenHh.getText() + "\"  khỏi hóa đơn chứ ? ")) {
            ctbhdao.delete(getForm());
        }
        fillTableThanhToan();
    }

    void btnSetOFF(Object... args) {
        btnTimKiem.setEnabled(true);
        btnUpdate.setEnabled(true);
        btnHuy.setEnabled(true);
        for (Object ob : args) {
            ((JButton) ob).setEnabled(false);
        }
    }

    void thanhToan() {
        if (BanHangSP.CheckMaBanHang()) {
            HoaDonJFrame tt = new HoaDonJFrame(this);
            tt.setVisible(true);
        } else {

        }
    }

    void updateHd() {
        if (BanHangSP.CheckMaBanHang()) {
            ctbhdao.update(getForm());
            fillTableThanhToan();
        } else {
            if (Message.confirm(this, "Chưa có hóa đơn Tạo Hóa đơn mới")) {
                try {
                    BanHangSP.setMaHoaDonBanHang(pbhdao.getMaPhieubanHangNeẉ̣());
                    HoaDonBanHang hhbh = new HoaDonBanHang();
                    hhbh.setMakh("kh1");
                    hhbh.setNgayhdbh(LocalDateTime.now());
                    hhbh.setManv(admin.user.getManv());
                    hdbhdao.insert(hhbh);
                } catch (SQLException ex) {
                    Logger.getLogger(BanHangJPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    void chonHangHoa() {
        if (BanHangSP.CheckMaBanHang()) {
            String ten = (String) tblHangHoa.getValueAt(tblHangHoa.getSelectedRow(), 0);
            HangHoa hh = hhdao.selectHHByName(ten);
            ChiTietBanHang ctbh = new ChiTietBanHang();
            ctbh.setMahdbd(BanHangSP.getMaHoaDonBanHang());
            ctbh.setMhh(hh.getMahh());
            ctbh.setSoluong(1);
            System.out.println(ctbh.getMahdbd());
            if (!ctbhdao.CheckExisting(ctbh)) {
                ctbhdao.insert(ctbh);
                fillTableThanhToan();
            } else {
                Message.alert(this, "Đã tồn tại trong hóa đơn ");
            }
        } else {
            if (Message.confirm(this, "Chưa có hóa đơn Tạo Hóa đơn mới")) {
                try {
                    BanHangSP.setMaHoaDonBanHang(pbhdao.getMaPhieubanHangNeẉ̣());
                    HoaDonBanHang hhbh = new HoaDonBanHang();
                    hhbh.setMakh("kh1");
                    hhbh.setNgayhdbh(LocalDateTime.now());
                    hhbh.setManv(admin.user.getManv());
                    hdbhdao.insert(hhbh);
                } catch (SQLException ex) {
                    Logger.getLogger(BanHangJPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }

    ChiTietBanHang getForm() {
        ChiTietBanHang ctbh = new ChiTietBanHang();
        ctbh.setMhh(txtTenHh.getName());
        ctbh.setMahdbd(BanHangSP.getMaHoaDonBanHang());
        ctbh.setSoluong(Integer.parseInt(txtSoLuong.getText()));
        return ctbh;
    }

    void resetForm() {
        setForm(new ChiTietBanHang());
        txtDonGia.setText("0");
        btnSetOFF(btnUpdate, btnHuy);
    }

    void setForm(ChiTietBanHang ctbh) {
        btnSetOFF();
        txtTenHh.setText(ctbh.getTenhh());
        txtSoLuong.setText(String.valueOf(ctbh.getSoluong()));
        txtDonGia.setText(String.valueOf(ctbh.getGiasp()));
        txtTenHh.setName(ctbh.getMhh());
    }

    void fillTableThanhToan() {
        DefaultTableModel model = (DefaultTableModel) tblThanhTien.getModel();
        model.setRowCount(0);
        if (BanHangSP.CheckMaBanHang()) {
            List<ChiTietBanHang> listhh = ctbhdao.selectAllbyHHBH(BanHangSP.getMaHoaDonBanHang());
            for (ChiTietBanHang ctbh : listhh) {
                Object[] row = new Object[3];
                row[0] = ctbh.getTenhh();
                row[1] = ctbh.getSoluong();
                row[2] = ctbh.getThanhtien();
                model.addRow(row);
            }
        }
        resetForm();
        btnSetOFF(btnUpdate, btnHuy);
    }

    void timkiem() {
        String keyword = txtTimKiem.getText();
        DefaultTableModel model = (DefaultTableModel) tblHangHoa.getModel();
        model.setRowCount(0);
        if (cboLoaiHang.getSelectedItem() != null) {
            List<ChiTietBanHang> listhh = ctbhdao.selectAllbyHHBH(BanHangSP.getMaHoaDonBanHang());
            for (ChiTietBanHang ctbh : listhh) {
                Object[] row = new Object[3];
                row[0] = ctbh.getTenhh();
                row[1] = ctbh.getSoluong();
                row[2] = ctbh.getThanhtien();
                model.addRow(row);
            }
        }
        if (tblHangHoa.getRowCount() == 0) {
            Message.alert(this, "Không tìm thấy " + keyword + " trong loại hàng " + ((LoaiHang) cboLoaiHang.getSelectedItem()).getTenlh());
            fillTableHangHoa();
        }
        txtTimKiem.setText("");
    }
    HangHoaDAO hhdao = new HangHoaDAO();
    ChiTietBanHangDAO ctbhdao = new ChiTietBanHangDAO();
    LoaiHangDAO lhdao = new LoaiHangDAO();
    HoaDonBanHangDAO hdbhdao = new HoaDonBanHangDAO();
    PhieuBanHangDAO pbhdao = new PhieuBanHangDAO();

    void fillComboBoxLoaiHang() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboLoaiHang.getModel();
        model.removeAllElements();
        List<LoaiHang> list = lhdao.selectAll();
        for (LoaiHang hh : list) {
            model.addElement(hh);
        }
        cboLoaiHang.setSelectedIndex(0);
        fillTableHangHoa();
    }

    void fillTableHangHoa() {
        DefaultTableModel model = (DefaultTableModel) tblHangHoa.getModel();
        model.setRowCount(0);
        if (cboLoaiHang.getSelectedItem() != null) {
            List<HangHoa> listhh = hhdao.selectByLH(((LoaiHang) cboLoaiHang.getSelectedItem()).getMalh());
            for (HangHoa hangHoa : listhh) {
                Object[] row = new Object[2];
                row[0] = hangHoa.getTenhh();
                row[1] = hangHoa.getGiasp();
                model.addRow(row);
            }
        }
    }
}
