/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelItem;

import com.API.Message;
import com.DAO.LoaiGiamGiaDAO;
import com.DAO.PhieuGiamGiaDAO;
import com.entity.LoaiGiamGia;
import com.entity.PhieuGiamGia;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RITTAM
 */
public class GiamGiaPanel extends javax.swing.JPanel {

    /**
     * Creates new form GiamGiaPanel
     */
    public GiamGiaPanel() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaGG = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtGiam = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHoaDonToiThieu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtGiamToiDa = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        chkTrangThai = new javax.swing.JCheckBox();
        cboLoaiGiamGia = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMaGiamGia = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField6.setText("jTextField1");

        jLabel6.setText("jLabel1");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã Giảm Giá :");

        jLabel2.setText("Loại Giảm Giá :");

        jLabel3.setText("Giảm :");

        jLabel4.setText("Hóa đơn tối thiểu :");

        jLabel5.setText("Giảm tối đa");

        jLabel7.setText("Tình trạng mã");

        jLabel8.setText("Số Lượng");

        chkTrangThai.setText("Sẵn sàng");

        cboLoaiGiamGia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMaGG, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(txtGiam, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboLoaiGiamGia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtHoaDonToiThieu, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtGiamToiDa, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(chkTrangThai)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(28, 28, 28))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtHoaDonToiThieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtGiamToiDa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(chkTrangThai)))
                            .addComponent(jLabel4))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(txtMaGG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(cboLoaiGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtGiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        tblMaGiamGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Giảm Giá", "Loại Giảm Giá", "Giảm", "Giá trị tối thiểu đơn hàng", "Giảm tối đa", "Tình Trạng mã", "Số Lượng mã Giảm Giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMaGiamGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMaGiamGiaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMaGiamGia);

        jScrollPane3.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa)
                .addGap(18, 18, 18)
                .addComponent(btnSua)
                .addGap(18, 18, 18)
                .addComponent(btnMoi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnSua)
                    .addComponent(btnMoi))
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        Them();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        xoa();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        sua();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        moi();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void tblMaGiamGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMaGiamGiaMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            PhieuGiamGia pgg = pggdao.SelectById((String) tblMaGiamGia.getValueAt(tblMaGiamGia.getSelectedRow(), 0));
            setForm(pgg);
            editable(txtGiam, txtGiamToiDa, txtHoaDonToiThieu, txtSoLuong);
        }
    }//GEN-LAST:event_tblMaGiamGiaMouseClicked
    boolean checkinput(Object... args) {
        for (Object txtinput : args) {
            try {
                String txt = ((JTextField) txtinput).getText().trim();
                if (txt.equals("") || txt.equals(" ")) {
                    Message.alert(this, "Không được để trống!!!!");
                    return false;
                }
            } catch (Exception e) {
            }
        }
        return true;
    }
    boolean check(){
        return checkinput(txtGiam, txtGiamToiDa, txtHoaDonToiThieu, txtSoLuong,txtMaGG)&&checkDulieu();
    }
    boolean checkDulieu() {
        boolean result = true;

        try {
            int giam = Integer.parseInt(txtGiam.getText());
            int hoadontoithieu = Integer.parseInt(txtHoaDonToiThieu.getText());
            int giamtoida = Integer.parseInt(txtGiamToiDa.getText());
            if (((LoaiGiamGia) cboLoaiGiamGia.getSelectedItem()).getLoaiGG().trim().equals("PHAMTRAM")) {
                if (giam >= 100 || giam <= 0) {
                    Message.alert(this,"Giảm % không dc nhỏ hơn 0");
                    result = false;
                }
            } else if (((LoaiGiamGia) cboLoaiGiamGia.getSelectedItem()).getLoaiGG().trim().equals("TIEN")) {
                if (giam<0||giamtoida<0||hoadontoithieu<0) {
                    Message.alert(this,"Giảm, Giảm tối đa, Giảm tối thiệu phải >=0");
                    result = false;
                }
            }
        } catch (NumberFormatException e) {
            Message.alert(this,"Giảm, Giảm tối đa, Giá trị tối thiểu phải là số nguyên");
            return false;
        }
        return result;
    }

    void filltable() {
        DefaultTableModel tablemodel = (DefaultTableModel) tblMaGiamGia.getModel();
        tablemodel.setRowCount(0);
        List<PhieuGiamGia> list = pggdao.selectAll();
        for (PhieuGiamGia pgg : list) {
            Object[] row = new Object[7];
            row[0] = pgg.getMapgg();
            row[1] = pgg.getLoaigg();
            row[2] = pgg.getGiam();
            row[3] = pgg.getGiatritoithieu();
            row[4] = pgg.getGiamtoida();
            row[5] = pgg.isTinhtrang()? "Bật":"Tắt";
            row[6] = pgg.getSoluong();
            tablemodel.addRow(row);
        }
    }

    void init() {
        fillComBoBoxLoaiGG();
        filltable();
    }
    PhieuGiamGiaDAO pggdao = new PhieuGiamGiaDAO();
    LoaiGiamGiaDAO lggdao = new LoaiGiamGiaDAO();

    void fillComBoBoxLoaiGG() {
        List<LoaiGiamGia> list = lggdao.SelectALL();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboLoaiGiamGia.getModel();
        model.removeAllElements();
        for (LoaiGiamGia lgg : list) {
            model.addElement(lgg);
        }
        cboLoaiGiamGia.setSelectedIndex(0);
    }

    void clearForm() {
        setForm(new PhieuGiamGia());
    }

    void setForm(PhieuGiamGia hh) {
        txtMaGG.setText(hh.getMapgg());
        txtGiamToiDa.setText(String.valueOf(hh.getGiamtoida()));
        txtHoaDonToiThieu.setText(String.valueOf(hh.getGiatritoithieu()));
        txtGiam.setText(String.valueOf(hh.getGiam()));
        txtSoLuong.setText(String.valueOf(hh.getSoluong()));
        chkTrangThai.setSelected(hh.isTinhtrang());
        if (hh.getLoaigg() != null) {
            cboLoaiGiamGia.setSelectedItem(new LoaiGiamGia(hh.getLoaigg()));
        }
        editable(txtGiamToiDa, txtHoaDonToiThieu, txtGiam, txtSoLuong);
        btnsetable(btnSua, btnXoa, btnMoi);
    }

    PhieuGiamGia getForm() {
        PhieuGiamGia hh = new PhieuGiamGia();
        hh.setMapgg(txtMaGG.getText());
        LoaiGiamGia lh = (LoaiGiamGia) cboLoaiGiamGia.getSelectedItem();
        hh.setLoaigg(lh.getLoaiGG());
        hh.setGiam(Integer.parseInt(txtGiam.getText()));
        hh.setGiamtoida(Integer.parseInt(txtGiamToiDa.getText()));
        hh.setGiatritoithieu(Integer.parseInt(txtHoaDonToiThieu.getText()));
        hh.setSoluong(Integer.parseInt(txtSoLuong.getText()));
        hh.setTinhtrang(chkTrangThai.isSelected());
        return hh;
    }

    void editable(Object... args) {
        txtGiam.setEditable(false);
        txtGiamToiDa.setEditable(false);
        txtHoaDonToiThieu.setEditable(false);
        txtSoLuong.setEditable(false);
        txtMaGG.setEditable(false);

        for (Object ob : args) {
            try {
                ((JTextField) ob).setEditable(true);
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }

    void btnsetable(Object... args) {
        btnMoi.setEnabled(false);
        btnSua.setEnabled(false);
        btnThem.setEnabled(false);
        btnXoa.setEnabled(false);
        for (Object ob : args) {
            try {
                ((JButton) ob).setEnabled(true);
            } catch (Exception e) {
                System.out.println(e);
            }
        }

    }

    void Them() {
        PhieuGiamGia hh = getForm();
        if (!check()) {
            Message.alert(this, "Kiểm Tra Đầu Vào");
        } else {
            try {
                pggdao.insert(hh);
                this.filltable();
                this.clearForm();
                Message.alert(this, "Thêm thành công!");
            } catch (Exception e) {
                Message.alert(this, "Thêm thất bại!");
                System.out.println(e);
            }
        }
    }

    void xoa() {
        PhieuGiamGia hh = getForm();
        if (hh.getMapgg().trim().equals("")) {
            Message.alert(this, "Chọn phiếu để xóa!");
        } else {
            if (Message.confirm(this, "Bạn muốn xóa " + "\"" + hh.getMapgg() + "\"" + " chứ?")) {
                try {
                    pggdao.delete(hh.getMapgg());
                    this.filltable();
                    this.clearForm();
                    Message.alert(this, "Xóa thành công!");
                } catch (Exception e) {
                    Message.alert(this, "Xóa thất bại!");
                }
            }
        }
    }

    void sua() {
        PhieuGiamGia hh = getForm();
        if (!check()) {
            Message.alert(this, "Chưa chọn Phiếu GG!!!");
        } else {
            PhieuGiamGia hh1 = pggdao.SelectById(hh.getMapgg().trim());
            if (Message.confirm(this, "Bạn muốn Sửa " + "\"" + hh.getMapgg() + "\"" + " trong kho chứ?"
                    + "\n Giảm: " + hh1.getGiam() + "  " + hh1.getLoaigg() + " --> " + hh.getGiam() + "  " + hh.getLoaigg()
                    + "\n Giá Trị Tối Thiểu " + String.valueOf(hh1.getGiatritoithieu()) + " --> " + String.valueOf(hh.getGiatritoithieu())
                    + "\n Giảm tối đa :" + hh1.getGiamtoida() + "--->" + hh.getGiamtoida()
                    + "\n Tình Trạng sản phẩm " + (hh.isTinhtrang() ? "Có thể sử dụng" : "tắt")
            )) {
                try {
                    pggdao.update(hh);
                    this.filltable();
                    this.clearForm();
                    Message.alert(this, "Sửa thành công!");
                } catch (Exception e) {
                    Message.alert(this, "Sửa thất bại!");
                    System.out.println(e);
                }
            }
        }
    }

    private void moi() {
        clearForm();
        editable(txtGiam, txtGiamToiDa, txtHoaDonToiThieu, txtMaGG, txtSoLuong);
        btnsetable(btnMoi, btnThem);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboLoaiGiamGia;
    private javax.swing.JCheckBox chkTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTable tblMaGiamGia;
    private javax.swing.JTextField txtGiam;
    private javax.swing.JTextField txtGiamToiDa;
    private javax.swing.JTextField txtHoaDonToiThieu;
    private javax.swing.JTextField txtMaGG;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables
}
