/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelItem;

import com.API.Message;
import com.DAO.HangHoaDAO;
import com.DAO.LoaiHangDAO;
import com.entity.HangHoa;
import com.entity.LoaiHang;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
//Xong !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
/**
 *
 * @author lamqw
 */
public class HangHoaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HangHoaJPanel
     */
    public HangHoaJPanel() {
        initComponents();
        init();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMahh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cboLoaiHang = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtTenHangHoa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        img = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHangHoa = new javax.swing.JTable();
        btnSua = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(77, 166, 255));
        jLabel1.setText("Hàng Hoá");

        jLabel2.setText("Mã hàng hoá:");

        jLabel3.setText("Tên loại hàng:");

        cboLoaiHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Tên hàng hoá:");

        jLabel6.setText("Giá:");

        img.setText("ảnh");
        img.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgMouseClicked(evt);
            }
        });

        tblHangHoa.setBackground(new java.awt.Color(77, 166, 255));
        tblHangHoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã loại hàng", "Mã hàng hoá", "Tên hàng hoá", "Giá "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHangHoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHangHoaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblHangHoa);

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jLabel1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel2)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMahh)
                            .addComponent(cboLoaiHang, 0, 269, Short.MAX_VALUE)
                            .addComponent(txtTenHangHoa)
                            .addComponent(txtGia, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(89, 89, 89)
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa)
                .addGap(12, 12, 12)
                .addComponent(btnSua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMoi)
                .addGap(35, 35, 35))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMahh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cboLoaiHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTenHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnSua)
                    .addComponent(btnMoi))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblHangHoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHangHoaMouseClicked
        // TODO add your handling code here:
          HangHoa hh = hhdao.SelectById((String) tblHangHoa.getValueAt(tblHangHoa.getSelectedRow(), 1));
        setForm(hh);
    }//GEN-LAST:event_tblHangHoaMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        sua();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        moi();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        xoa();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        Them();
    }//GEN-LAST:event_btnThemActionPerformed

    private void imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            chonAnh();
        } catch (IOException ex) {
            Message.alert(this, "Lỗi Không thể chọn ảnh");
        }
    }//GEN-LAST:event_imgMouseClicked

    void init() {
        fillComboBoxLoaiHang();
        filltable();
    }

    HangHoaDAO hhdao = new HangHoaDAO();
    LoaiHangDAO lhdao = new LoaiHangDAO();

    void filltable() {
        DefaultTableModel model = (DefaultTableModel) tblHangHoa.getModel();
        model.setRowCount(0);
        List<HangHoa> list = hhdao.selectAll();
        for (HangHoa hh : list) {
            Object[] row = new Object[4];
            row[0] = hh.getMalh();
            row[1] = hh.getMahh();
            row[2] = hh.getTenhh();
            row[3] = hh.getGiasp();
            model.addRow(row);
        }
        img.setIcon(no_image_icon);
        btnsetable(btnMoi,btnThem);
    }

    void fillComboBoxLoaiHang() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboLoaiHang.getModel();
        model.removeAllElements();
        List<LoaiHang> list = lhdao.selectAll();
        for (LoaiHang hh : list) {
            model.addElement(hh);
        }
    }

    void clearForm() {
        setForm(new HangHoa());
    }

    void setForm(HangHoa hh) {
        txtMahh.setText(hh.getMahh());
        txtGia.setText(String.valueOf(hh.getGiasp()));
        txtTenHangHoa.setText(hh.getTenhh());
        if(hh.getMalh()!=null){
        cboLoaiHang.setSelectedItem(new LoaiHang(hh.getMalh()));
        }
        if(hh.getHinhanh()!=null){
            bytes = hh.getHinhanh();
            img.setIcon(new ImageIcon(hh.getHinhanh()));
        }else{
            img.setIcon(no_image_icon);
            bytes = null;
        }
        editable(txtTenHangHoa,txtGia);
        btnsetable(btnSua,btnXoa,btnMoi);
    }

    HangHoa getForm() {
        HangHoa hh = new HangHoa();
        hh.setMahh(txtMahh.getText());
        if(bytes!=null){
        hh.setHinhanh(bytes);
        }else{
            try {
                hh.setHinhanh((new FileInputStream((new File("")).getAbsolutePath()+"\\src\\img\\noimage.png")).readAllBytes());
            } catch (IOException ex) {
                System.out.println("anh bị lỗi");
            }
        }
        LoaiHang lh =(LoaiHang) cboLoaiHang.getSelectedItem();
        hh.setMalh(lh.getMalh());
        hh.setTenhh(txtTenHangHoa.getText());
        hh.setGiasp(Integer.parseInt(txtGia.getText()));
        return hh;
    }

    void editable(Object... args) {
        txtGia.setEditable(false);
        txtMahh.setEditable(false);
        txtTenHangHoa.setEditable(false);
        for (Object ob : args) {
            try {
                ((JTextField) ob).setEditable(true);
            } catch (Exception e) {
                System.out.println(e);
            }
        }

    }

    byte[] bytes = null;
    void btnsetable(Object... args) {
        btnMoi.setEnabled(false);
        btnSua.setEnabled(false);
        btnThem.setEnabled(false);
        btnXoa.setEnabled(false);
        for (Object ob : args) {
            try {
                ((JButton) ob).setEnabled(true);
            } catch (Exception e) {
                System.out.println(e);
            }
        }

    }

    void chonAnh() throws IOException {
        try {
            JFileChooser jFileChooser = new JFileChooser();
            int responsive = jFileChooser.showOpenDialog(null);
            if (responsive == JFileChooser.APPROVE_OPTION) {
                File file = new File(jFileChooser.getSelectedFile().getAbsolutePath());
                ImageIcon icon = new ImageIcon(file.getAbsolutePath());
                img.setIcon(icon);
                icon.getImage();
                FileInputStream fis = new FileInputStream(file);
                bytes = fis.readAllBytes();
                fis.close();
                System.out.println("Chọn ảnh thành công");
            }
        } catch (Exception e) {
            Message.alert(null, "Chon Ảnh lỗi!!!!");
            img.setIcon(new ImageIcon());
            bytes = null;
            throw new RuntimeException(e);
        }
    }
    void Them() {
        HangHoa hh = getForm();
        if (hh.getTenhh().trim().equals("")) {
            Message.alert(this, "Chưa nhập tên");
        }else{
        try {
            hhdao.insert(hh);
            this.filltable();
            this.clearForm();
            Message.alert(this, "Thêm thành công!");
        } catch (Exception e) {
            Message.alert(this, "Thêm thất bại!");
            System.out.println(e);
        }
        }
    }

    void xoa() {
        HangHoa hh = getForm();
        if (hh.getMahh().trim().equals("")) {
            Message.alert(this, "Chọn Hàng để xóa!");
        } else {
            if (Message.confirm(this, "Bạn muốn xóa " + "\""+ hh.getTenhh()+ "\""+ " khỏi menu chứ?")) {
                try {
                    hhdao.delete(hh.getMahh());
                    this.filltable();
                    this.clearForm();
                    Message.alert(this, "Xóa thành công!");
                } catch (Exception e) {
                    Message.alert(this, "Xóa thất bại!");
                }
            }
        }
    }

    void sua() {
        HangHoa hh = getForm();
        if(hh.getMahh().trim().equals("")){
            Message.alert(this, "Chưa Chọn Hàng hóa!!!");
        }
        else{
        HangHoa hh1 = hhdao.SelectById(hh.getMahh().trim());
            if (Message.confirm(this, "Bạn muốn Sửa " + "\""+ hh.getMahh()+ "\""+ " trong kho chứ?" +
                    "\n Tên Hàng Hóa "+ hh1.getTenhh()+ " --> " +hh.getTenhh()+
                    "\n Mã loại Hàng "+ hh1.getMalh()+ " --> " +hh.getMalh()+
                    "\n Gía Sản Phẩm "+ hh1.getGiasp()+ " --> "+ hh.getGiasp())) {
                try {
                    hhdao.update(hh);
                    this.filltable();
                    this.clearForm();
                    Message.alert(this, "Sửa thành công!");
                } catch (Exception e) {
                    Message.alert(this, "Sửa thất bại!");
                    System.out.println(e);
                }
            }
        }
    }

    private void moi() {
        clearForm();
        editable(txtGia,txtTenHangHoa,txtMahh);
        btnsetable(btnMoi,btnThem);
    }
    ImageIcon no_image_icon = new ImageIcon((new File("")).getAbsolutePath()+"\\src\\img\\noimage.png");
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboLoaiHang;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblHangHoa;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMahh;
    private javax.swing.JTextField txtTenHangHoa;
    // End of variables declaration//GEN-END:variables
}
