/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package panelItem;

import com.API.Message;
import com.DAO.ChiTietBanHangDAO;
import com.DAO.HoaDonBanHangDAO;
import com.DAO.PhieuGiamGiaDAO;
import com.SUPPORT.BanHangSP;
import com.entity.ChiTietBanHang;
import com.entity.HoaDonBanHang;
import com.entity.PhieuGiamGia;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lamqw
 */
public class HoaDonJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ThanhToanJFrame
     */
    public HoaDonJFrame(BanHangJPanel PanelbanHang) {
        this.mahhdh = BanHangSP.getMaHoaDonBanHang();
        this.PanelbanHang = PanelbanHang;
        initComponents();
        init();
    }
    BanHangJPanel PanelbanHang;
    String mahhdh;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMahhbh = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtGiamGia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtChiPhiKhac = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThanhTien = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JLabel();
        cboPGG = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnInHoaDon = new javax.swing.JButton();
        btnHuyHoaDon = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(77, 166, 255));
        jLabel1.setText("Hoá đơn");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(77, 166, 255), null), "Chi tiết", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel5.setText("Mã hoá đơn:");

        jLabel6.setText("Món ORDER:");

        txtMahhbh.setText("ABC1222");

        jLabel3.setText("Mã nhân viên:");

        txtTenNV.setText("Vũ Văn Thật");

        jLabel7.setText("Giảm giá:");

        txtGiamGia.setEditable(false);
        txtGiamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiamGiaActionPerformed(evt);
            }
        });
        txtGiamGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtGiamGiaKeyPressed(evt);
            }
        });

        jLabel8.setText("Chi phí khác:");

        txtChiPhiKhac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtChiPhiKhacKeyPressed(evt);
            }
        });

        tblThanhTien.setBackground(new java.awt.Color(77, 166, 255));
        tblThanhTien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên hàng", "Số lượng", "Giá", "Thành Tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblThanhTien);

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel9.setText("Tổng tiền:");

        txtTongTien.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtTongTien.setForeground(new java.awt.Color(0, 255, 51));
        txtTongTien.setText("1.000.000 VND");

        cboPGG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboPGG.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                cboPGGHierarchyChanged(evt);
            }
        });
        cboPGG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPGGActionPerformed(evt);
            }
        });

        jLabel2.setText("PGG");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txtTongTien))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtMahhbh, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(27, 27, 27)
                                        .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtChiPhiKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cboPGG, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 41, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMahhbh)
                    .addComponent(jLabel3)
                    .addComponent(txtTenNV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtChiPhiKhac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboPGG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTongTien))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        btnInHoaDon.setBackground(new java.awt.Color(77, 166, 255));
        btnInHoaDon.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnInHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btnInHoaDon.setText("In hoá đơn");
        btnInHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInHoaDonActionPerformed(evt);
            }
        });

        btnHuyHoaDon.setBackground(new java.awt.Color(77, 166, 255));
        btnHuyHoaDon.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnHuyHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btnHuyHoaDon.setText("Hủy Hóa Đơn");
        btnHuyHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyHoaDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(288, 288, 288)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btnInHoaDon)
                                .addGap(32, 32, 32)
                                .addComponent(btnHuyHoaDon)))
                        .addGap(0, 290, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInHoaDon)
                    .addComponent(btnHuyHoaDon))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyHoaDonActionPerformed
        // TODO add your handling code here:
        HuyHoaDon();
    }//GEN-LAST:event_btnHuyHoaDonActionPerformed

    private void btnInHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInHoaDonActionPerformed
        // TODO add your handling code here:
        InHoaDon();
    }//GEN-LAST:event_btnInHoaDonActionPerformed

    private void txtGiamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiamGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiamGiaActionPerformed

    private void txtGiamGiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiamGiaKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtGiamGiaKeyPressed

    private void txtChiPhiKhacKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChiPhiKhacKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            UpdateChiPhi();
        }
    }//GEN-LAST:event_txtChiPhiKhacKeyPressed

    private void cboPGGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPGGActionPerformed
        UpdateGiamGia();
    }//GEN-LAST:event_cboPGGActionPerformed

    private void cboPGGHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_cboPGGHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPGGHierarchyChanged

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuyHoaDon;
    private javax.swing.JButton btnInHoaDon;
    private javax.swing.JComboBox<String> cboPGG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblThanhTien;
    private javax.swing.JTextField txtChiPhiKhac;
    private javax.swing.JTextField txtGiamGia;
    private javax.swing.JLabel txtMahhbh;
    private javax.swing.JLabel txtTenNV;
    private javax.swing.JLabel txtTongTien;
    // End of variables declaration//GEN-END:variables
     void init() {
        this.setLocationRelativeTo(null);
        fillTable();
        fillcboPhieuGG();
        setForm();
    }

    void setForm() {
        hdbhdao.resetTongtien(mahhdh);
        HoaDonBanHang hdbh = hdbhdao.SelectById(mahhdh);
//        txtTenNV.setText(admin.user.getTennv());
        txtChiPhiKhac.setText(String.valueOf(hdbh.getChiphikhac()));
        txtGiamGia.setText(String.valueOf(hdbh.getGiamgia()));
        txtTongTien.setText(String.valueOf(hdbh.getTongtien() + " Vnđ"));
    }
    ChiTietBanHangDAO ctbhdao = new ChiTietBanHangDAO();
    HoaDonBanHangDAO hdbhdao = new HoaDonBanHangDAO();

    void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblThanhTien.getModel();
        model.setRowCount(0);
        List<ChiTietBanHang> listhh = ctbhdao.selectAllbyHHBH(mahhdh);
        for (ChiTietBanHang ctbh : listhh) {
            Object[] row = new Object[4];
            row[0] = ctbh.getTenhh();
            row[1] = ctbh.getSoluong();
            row[2] = ctbh.getGiasp();
            row[3] = ctbh.getThanhtien();
            model.addRow(row);
        }
    }
    PhieuGiamGiaDAO pggdao = new PhieuGiamGiaDAO();

    void fillcboPhieuGG() {
        List<PhieuGiamGia> list = pggdao.selectAll();
        if (!list.isEmpty()) {
            DefaultComboBoxModel model = (DefaultComboBoxModel) cboPGG.getModel();
            model.removeAllElements();
            for (PhieuGiamGia pgg : list) {
                if (pgg.getGiatritoithieu() < hdbhdao.selectTongBill(mahhdh)) {
                    model.addElement(pgg);
                }
            }
            if (cboPGG.getItemCount() > 0) {
                cboPGG.setSelectedIndex(0);
            }
        } else {
            cboPGG.setEditable(false);
        }
    }

    void UpdateChiPhi() {
        try {
            int chiphikhac = Integer.parseInt(txtChiPhiKhac.getText());
            hdbhdao.updateChiPhi(chiphikhac, mahhdh);
            setForm();
        } catch (NumberFormatException e) {
            System.out.println(e);
            Message.alert(this, "Kiểm tra lại Đầu vào....");
        }
    }

    void UpdateGiamGia() {
        if (cboPGG.getSelectedItem() != null) {
            try {
                String maGiamGia = ((PhieuGiamGia) cboPGG.getSelectedItem()).getMapgg();
                hdbhdao.updateMaGiamGia(maGiamGia, mahhdh);
                setForm();
            } catch (NumberFormatException e) {
                System.out.println(e);
                Message.alert(this, "Kiểm tra lại mã Giảm Giá ...");
            }
        }
    }

    void InHoaDon() {
        Message.alert(this, "In hoa don thanh cong");
        BanHangSP.resetMaBanHang();
        PanelbanHang.fillTableThanhToan();
        this.setVisible(false);
    }

    void HuyHoaDon() {
        if (Message.confirm(this, "Bạn chắc chắn hủy hóa đơn bên trên chứ ? ")) {
            hdbhdao.delete(mahhdh);
            BanHangSP.resetMaBanHang();
            PanelbanHang.fillTableThanhToan();
            this.setVisible(false);
        } else {
            Message.alert(this, "Hủy hóa đơn Thất bại");
        }

    }
}
