/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelItem;

import com.API.DateSP;
import com.API.Message;
import com.API.admin;
import com.DAO.PhieuChiDAO;
import com.entity.PhieuChi;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lamqw
 */
public class PhieuChiJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PhieuChiJPanel
     */
    public PhieuChiJPanel() {
        initComponents();
        init();
    }
    PhieuChiDAO dao = new PhieuChiDAO();

    void init() {
        fillTable();
    }

    void btnsetable(Object... args) {
        btnSua.setEnabled(false);
        btnThem.setEnabled(false);
        for (Object ob : args) {
            try {
                ((JButton) ob).setEnabled(true);
            } catch (Exception e) {
                System.out.println(e);
            }
        }

    }

    void fillTable() {
        List<PhieuChi> list = dao.selectAll();
        DefaultTableModel model = (DefaultTableModel) tblPhieuChi.getModel();
        model.setRowCount(0);
        for (PhieuChi phieuchi : list) {
            Object[] row = new Object[5];
            row[0] = phieuchi.getMaphieuchi();
            row[1] = phieuchi.getSotienchi();
            row[2] = phieuchi.getLydo();
            row[3] = phieuchi.getManv();
            if (phieuchi.getThoigian() != null) {
                row[4] = DateSP.DateTimeToString(phieuchi.getThoigian(), DateSP.getDatetimepattern());
            }
            model.addRow(row);
        }
        btnsetable(btnThem);
    }

    void clearForm() {
        setForm(new PhieuChi());
    }

    void setForm(PhieuChi phieuChi) {
        txtSoTien.setText(String.valueOf(phieuChi.getSotienchi()));
        txtLyDo.setText(phieuChi.getLydo());
        if (phieuChi.getThoigian() != null) {
            txtTime.setText(DateSP.DateTimeToString(phieuChi.getThoigian(), DateSP.getDatetimepattern()));
        }
        editable();
        txtLyDo.setEditable(false);
    }

    PhieuChi getForm() {
        PhieuChi phieuChi = new PhieuChi();
        phieuChi.setLydo(txtLyDo.getText());
        phieuChi.setSotienchi(Integer.parseInt(txtSoTien.getText()));
        phieuChi.setManv(admin.user.getManv());
        phieuChi.setThoigian(LocalDateTime.now());
        return phieuChi;
    }

    void editable(Object... args) {
        txtSoTien.setEditable(false);
        for (Object ob : args) {
            try {
                ((JTextField) ob).setEditable(true);
            } catch (Exception e) {
                System.out.println(e);
            }
        }

    }

    void Them() {
        PhieuChi phieuChi = getForm();
        if (phieuChi.getLydo().trim().equals("")) {
            Message.alert(this, "Chưa nhập lý do");
        } else {
            try {
                dao.insert(phieuChi);
                this.fillTable();
                this.clearForm();
                Message.alert(this, "Thêm thành công!");
            } catch (Exception e) {
                Message.alert(this, "Thêm thất bại!");
                System.out.println(e);
            }
        }
    }

    void xoa() {
        PhieuChi phieuChi = dao.SelectById((String) tblPhieuChi.getValueAt(tblPhieuChi.getSelectedRow(), 0));
        if (phieuChi.getMaphieuchi().trim().equals("")) {
            Message.alert(this, "Chọn Phiếu Chi để xóa!");
        } else {
            if (Message.confirm(this, "Bạn muốn xóa " + "\"" + phieuChi.getMaphieuchi().trim() + "\"" + " chứ?")) {
                try {
                    dao.delete(phieuChi.getMaphieuchi().trim());
                    this.fillTable();
                    this.clearForm();
                    Message.alert(this, "Xóa thành công!");
                } catch (Exception e) {
                    Message.alert(this, "Xóa thất bại!");
                }
            }
        }
    }

    private void moi() {
        clearForm();
        editable(txtSoTien);
        txtLyDo.setEditable(true);
        btnsetable(btnMoi, btnThem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSoTien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLyDo = new javax.swing.JTextArea();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPhieuChi = new javax.swing.JTable();
        txtTime = new javax.swing.JLabel();
        txtTime1 = new javax.swing.JLabel();
        btnMoi = new javax.swing.JButton();

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(77, 166, 255));
        jLabel1.setText("Phiếu chi");

        jLabel2.setText("Số tiền:");

        jLabel3.setText("Lý do:");

        txtLyDo.setColumns(20);
        txtLyDo.setRows(5);
        jScrollPane1.setViewportView(txtLyDo);

        btnThem.setBackground(new java.awt.Color(0, 255, 0));
        btnThem.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(255, 204, 102));
        btnSua.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Xóa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        tblPhieuChi.setBackground(new java.awt.Color(77, 166, 255));
        tblPhieuChi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Phiếu", "Số Tiền", "Lý Do", "Mã Nhân Viên", "Thời Gian"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPhieuChi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhieuChiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPhieuChi);

        btnMoi.setBackground(new java.awt.Color(77, 166, 255));
        btnMoi.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtSoTien, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(262, 262, 262)
                                .addComponent(jLabel1))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(btnThem)
                                .addGap(33, 33, 33)
                                .addComponent(btnSua)
                                .addGap(33, 33, 33)
                                .addComponent(btnMoi)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(227, 227, 227)
                    .addComponent(txtTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(397, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSoTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnMoi))
                .addGap(51, 51, 51))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(336, 336, 336)
                    .addComponent(txtTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(337, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblPhieuChiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhieuChiMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            PhieuChi phieuChi = dao.SelectById((String) tblPhieuChi.getValueAt(tblPhieuChi.getSelectedRow(), 0));
            setForm(phieuChi);
            editable();
            txtLyDo.setEditable(false);
            btnsetable(btnSua);
        }

    }//GEN-LAST:event_tblPhieuChiMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (admin.isLogin()) {
            this.Them();
        } else {
            Message.alert(this, "Đăng Nhập để sử dụng chức năng");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if (admin.isLogin()) {
            this.xoa();
        } else {
            Message.alert(this, "Đăng Nhập để sử dụng chức năng");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        this.moi();
    }//GEN-LAST:event_btnMoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPhieuChi;
    private javax.swing.JTextArea txtLyDo;
    private javax.swing.JTextField txtSoTien;
    private javax.swing.JLabel txtTime;
    private javax.swing.JLabel txtTime1;
    // End of variables declaration//GEN-END:variables
}
