/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javacafe;

import com.API.Message;
import com.API.admin;
import com.DAO.HoaDonBanHangDAO;
import com.SUPPORT.BanHangSP;
import java.awt.Color;
import javax.swing.JPanel;
import panelItem.BanHangJPanel;
import panelItem.ChamCongJPanel;
import panelItem.DangNhap;
import panelItem.DoiMatKhauPanel;
import panelItem.GiamGiaPanel;
import panelItem.HangHoaJPanel;
import panelItem.KhoHangJPanel;
import panelItem.LSGDJPanel;
import panelItem.PhieuChiJPanel;
import panelItem.QLKhachHangJPanel;
import panelItem.QLLuongJPanel;
import panelItem.QLNhanVienJPanel;
import panelItem.ThongKeDoanhThuJPanel;
import panelItem.ThongKeLuongJPanel;

/**
 *
 * @author lamqw
 */
public class MainQuanLyQuanCafe extends javax.swing.JFrame {
    
    Color colorReChuot = new Color(179, 218, 255);
    Color colorMacDinh = new Color(77, 169, 255);
    Color colorClick = new Color(26, 144, 255);
    
    /**
     * Creates new form MainQuanLyQuanCafe
     */
    public MainQuanLyQuanCafe() {
        initComponents();
        init();
    }
    
    void setPanel(JPanel panel){
        JPnMainView.removeAll();
        JPnMainView.add(panel);
        JPnMainView.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JPnMenu = new javax.swing.JPanel();
        JPnLogo = new javax.swing.JPanel();
        tblLogo = new javax.swing.JLabel();
        tblThongtin = new javax.swing.JLabel();
        JPnAcc = new javax.swing.JPanel();
        tblTenNV = new javax.swing.JLabel();
        JPnCPass = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        JPnLogout = new javax.swing.JPanel();
        Logout = new javax.swing.JLabel();
        tblDichVu = new javax.swing.JLabel();
        JPnBanHang = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        JPnHangHoa = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        JPnKhoHang = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        JPnPhieuChi = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        JPnQuanLyKhachHang = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        JPnQuanLyLuong = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        JPnQuanLyNhanVien = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        JPnThongKeDoanhThu = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        JPnThongKeLuong = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        JPnLichSuGiaoDich = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        JPnChamCong = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        JPnMainView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        JPnMenu.setBackground(new java.awt.Color(77, 166, 255));

        JPnLogo.setBackground(new java.awt.Color(77, 166, 255));

        tblLogo.setFont(new java.awt.Font("Verdana", 1, 27)); // NOI18N
        tblLogo.setForeground(new java.awt.Color(255, 255, 255));
        tblLogo.setText("Coffee FPoly");

        javax.swing.GroupLayout JPnLogoLayout = new javax.swing.GroupLayout(JPnLogo);
        JPnLogo.setLayout(JPnLogoLayout);
        JPnLogoLayout.setHorizontalGroup(
            JPnLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnLogoLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(tblLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPnLogoLayout.setVerticalGroup(
            JPnLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnLogoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(tblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tblThongtin.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        tblThongtin.setForeground(new java.awt.Color(255, 255, 255));
        tblThongtin.setText("Thông tin");

        JPnAcc.setBackground(new java.awt.Color(77, 166, 255));

        tblTenNV.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        tblTenNV.setForeground(new java.awt.Color(255, 255, 255));
        tblTenNV.setText(" Nguyễn Tuấn Lâm");

        javax.swing.GroupLayout JPnAccLayout = new javax.swing.GroupLayout(JPnAcc);
        JPnAcc.setLayout(JPnAccLayout);
        JPnAccLayout.setHorizontalGroup(
            JPnAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnAccLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(tblTenNV)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        JPnAccLayout.setVerticalGroup(
            JPnAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPnAccLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tblTenNV)
                .addContainerGap())
        );

        JPnCPass.setBackground(new java.awt.Color(77, 166, 255));
        JPnCPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPnCPassMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPnCPassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPnCPassMouseExited(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(153, 204, 255));
        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" Change Password");

        javax.swing.GroupLayout JPnCPassLayout = new javax.swing.GroupLayout(JPnCPass);
        JPnCPass.setLayout(JPnCPassLayout);
        JPnCPassLayout.setHorizontalGroup(
            JPnCPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnCPassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPnCPassLayout.setVerticalGroup(
            JPnCPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnCPassLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        JPnLogout.setBackground(new java.awt.Color(77, 166, 255));
        JPnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPnLogoutMouseExited(evt);
            }
        });

        Logout.setBackground(new java.awt.Color(153, 204, 255));
        Logout.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText(" Log out");
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        Logout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LogoutKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout JPnLogoutLayout = new javax.swing.GroupLayout(JPnLogout);
        JPnLogout.setLayout(JPnLogoutLayout);
        JPnLogoutLayout.setHorizontalGroup(
            JPnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPnLogoutLayout.setVerticalGroup(
            JPnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPnLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblDichVu.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        tblDichVu.setForeground(new java.awt.Color(255, 255, 255));
        tblDichVu.setText("Dịch vụ");

        JPnBanHang.setBackground(new java.awt.Color(77, 166, 255));
        JPnBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPnBanHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPnBanHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPnBanHangMouseExited(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(153, 204, 255));
        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bán hàng");
        jLabel5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel5KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout JPnBanHangLayout = new javax.swing.GroupLayout(JPnBanHang);
        JPnBanHang.setLayout(JPnBanHangLayout);
        JPnBanHangLayout.setHorizontalGroup(
            JPnBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnBanHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPnBanHangLayout.setVerticalGroup(
            JPnBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPnBanHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPnHangHoa.setBackground(new java.awt.Color(77, 166, 255));
        JPnHangHoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPnHangHoaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPnHangHoaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPnHangHoaMouseExited(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(153, 204, 255));
        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hàng hoá");
        jLabel6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel6KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout JPnHangHoaLayout = new javax.swing.GroupLayout(JPnHangHoa);
        JPnHangHoa.setLayout(JPnHangHoaLayout);
        JPnHangHoaLayout.setHorizontalGroup(
            JPnHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnHangHoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPnHangHoaLayout.setVerticalGroup(
            JPnHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPnHangHoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPnKhoHang.setBackground(new java.awt.Color(77, 166, 255));
        JPnKhoHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPnKhoHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPnKhoHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPnKhoHangMouseExited(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(153, 204, 255));
        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Kho hàng");
        jLabel7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel7KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout JPnKhoHangLayout = new javax.swing.GroupLayout(JPnKhoHang);
        JPnKhoHang.setLayout(JPnKhoHangLayout);
        JPnKhoHangLayout.setHorizontalGroup(
            JPnKhoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnKhoHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPnKhoHangLayout.setVerticalGroup(
            JPnKhoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPnKhoHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPnPhieuChi.setBackground(new java.awt.Color(77, 166, 255));
        JPnPhieuChi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPnPhieuChiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPnPhieuChiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPnPhieuChiMouseExited(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(153, 204, 255));
        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Phiếu chi");
        jLabel8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel8KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout JPnPhieuChiLayout = new javax.swing.GroupLayout(JPnPhieuChi);
        JPnPhieuChi.setLayout(JPnPhieuChiLayout);
        JPnPhieuChiLayout.setHorizontalGroup(
            JPnPhieuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnPhieuChiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPnPhieuChiLayout.setVerticalGroup(
            JPnPhieuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPnPhieuChiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPnQuanLyKhachHang.setBackground(new java.awt.Color(77, 166, 255));
        JPnQuanLyKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPnQuanLyKhachHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPnQuanLyKhachHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPnQuanLyKhachHangMouseExited(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(153, 204, 255));
        jLabel10.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Quản lý khách hàng");
        jLabel10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel10KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout JPnQuanLyKhachHangLayout = new javax.swing.GroupLayout(JPnQuanLyKhachHang);
        JPnQuanLyKhachHang.setLayout(JPnQuanLyKhachHangLayout);
        JPnQuanLyKhachHangLayout.setHorizontalGroup(
            JPnQuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnQuanLyKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPnQuanLyKhachHangLayout.setVerticalGroup(
            JPnQuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPnQuanLyKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPnQuanLyLuong.setBackground(new java.awt.Color(77, 166, 255));
        JPnQuanLyLuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPnQuanLyLuongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPnQuanLyLuongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPnQuanLyLuongMouseExited(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(153, 204, 255));
        jLabel11.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Quản lý lương");
        jLabel11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel11KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout JPnQuanLyLuongLayout = new javax.swing.GroupLayout(JPnQuanLyLuong);
        JPnQuanLyLuong.setLayout(JPnQuanLyLuongLayout);
        JPnQuanLyLuongLayout.setHorizontalGroup(
            JPnQuanLyLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnQuanLyLuongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPnQuanLyLuongLayout.setVerticalGroup(
            JPnQuanLyLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPnQuanLyLuongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPnQuanLyNhanVien.setBackground(new java.awt.Color(77, 166, 255));
        JPnQuanLyNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPnQuanLyNhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPnQuanLyNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPnQuanLyNhanVienMouseExited(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(153, 204, 255));
        jLabel12.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Quản lý nhân viên");
        jLabel12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel12KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout JPnQuanLyNhanVienLayout = new javax.swing.GroupLayout(JPnQuanLyNhanVien);
        JPnQuanLyNhanVien.setLayout(JPnQuanLyNhanVienLayout);
        JPnQuanLyNhanVienLayout.setHorizontalGroup(
            JPnQuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnQuanLyNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPnQuanLyNhanVienLayout.setVerticalGroup(
            JPnQuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPnQuanLyNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPnThongKeDoanhThu.setBackground(new java.awt.Color(77, 166, 255));
        JPnThongKeDoanhThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPnThongKeDoanhThuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPnThongKeDoanhThuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPnThongKeDoanhThuMouseExited(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(153, 204, 255));
        jLabel13.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Thông kê doanh thu");
        jLabel13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel13KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout JPnThongKeDoanhThuLayout = new javax.swing.GroupLayout(JPnThongKeDoanhThu);
        JPnThongKeDoanhThu.setLayout(JPnThongKeDoanhThuLayout);
        JPnThongKeDoanhThuLayout.setHorizontalGroup(
            JPnThongKeDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnThongKeDoanhThuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPnThongKeDoanhThuLayout.setVerticalGroup(
            JPnThongKeDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPnThongKeDoanhThuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPnThongKeLuong.setBackground(new java.awt.Color(77, 166, 255));
        JPnThongKeLuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPnThongKeLuongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPnThongKeLuongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPnThongKeLuongMouseExited(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(153, 204, 255));
        jLabel14.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Thông kê lương");
        jLabel14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel14KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout JPnThongKeLuongLayout = new javax.swing.GroupLayout(JPnThongKeLuong);
        JPnThongKeLuong.setLayout(JPnThongKeLuongLayout);
        JPnThongKeLuongLayout.setHorizontalGroup(
            JPnThongKeLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnThongKeLuongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPnThongKeLuongLayout.setVerticalGroup(
            JPnThongKeLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPnThongKeLuongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPnLichSuGiaoDich.setBackground(new java.awt.Color(77, 166, 255));
        JPnLichSuGiaoDich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPnLichSuGiaoDichMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPnLichSuGiaoDichMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPnLichSuGiaoDichMouseExited(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(153, 204, 255));
        jLabel15.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Lịch sử giao dịch");
        jLabel15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel15KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout JPnLichSuGiaoDichLayout = new javax.swing.GroupLayout(JPnLichSuGiaoDich);
        JPnLichSuGiaoDich.setLayout(JPnLichSuGiaoDichLayout);
        JPnLichSuGiaoDichLayout.setHorizontalGroup(
            JPnLichSuGiaoDichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnLichSuGiaoDichLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPnLichSuGiaoDichLayout.setVerticalGroup(
            JPnLichSuGiaoDichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPnLichSuGiaoDichLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPnChamCong.setBackground(new java.awt.Color(77, 166, 255));
        JPnChamCong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPnChamCongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPnChamCongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPnChamCongMouseExited(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(153, 204, 255));
        jLabel16.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Chấm Công");
        jLabel16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel16KeyPressed(evt);
            }
        });

        jButton2.setText("PhieuGiamGia");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPnChamCongLayout = new javax.swing.GroupLayout(JPnChamCong);
        JPnChamCong.setLayout(JPnChamCongLayout);
        JPnChamCongLayout.setHorizontalGroup(
            JPnChamCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnChamCongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(14, 14, 14))
        );
        JPnChamCongLayout.setVerticalGroup(
            JPnChamCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPnChamCongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPnChamCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2)))
        );

        jButton1.setText("Thoát Ứng dụng");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPnMenuLayout = new javax.swing.GroupLayout(JPnMenu);
        JPnMenu.setLayout(JPnMenuLayout);
        JPnMenuLayout.setHorizontalGroup(
            JPnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPnLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPnMenuLayout.createSequentialGroup()
                .addGroup(JPnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPnMenuLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(tblDichVu))
                    .addGroup(JPnMenuLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JPnAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPnMenuLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(JPnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JPnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JPnCPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JPnBanHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JPnHangHoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JPnKhoHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JPnPhieuChi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JPnQuanLyKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JPnQuanLyLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JPnQuanLyNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JPnThongKeDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JPnThongKeLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JPnLichSuGiaoDich, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JPnChamCong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(16, 16, 16))
            .addGroup(JPnMenuLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(JPnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblThongtin))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPnMenuLayout.setVerticalGroup(
            JPnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnMenuLayout.createSequentialGroup()
                .addComponent(JPnLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tblThongtin)
                .addGap(4, 4, 4)
                .addComponent(JPnAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPnCPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tblDichVu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JPnBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPnHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPnKhoHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPnPhieuChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPnQuanLyKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPnQuanLyLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPnQuanLyNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPnThongKeDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPnThongKeLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPnLichSuGiaoDich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPnChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        JPnMainView.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(JPnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPnMainView, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPnMainView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JPnCPassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnCPassMouseEntered
        // TODO add your handling code here:              
        JPnCPass.setBackground(colorReChuot);
    }//GEN-LAST:event_JPnCPassMouseEntered

    private void JPnCPassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnCPassMouseExited
        // TODO add your handling code here:     
        JPnCPass.setBackground(colorMacDinh);
    }//GEN-LAST:event_JPnCPassMouseExited

    private void JPnCPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnCPassMouseClicked
        // TODO add your handling code here:       
        if(admin.isLogin()){
        JPnCPass.setBackground(colorClick);
        setPanel(new DoiMatKhauPanel());}
        else{
                    Message.alert(this, "Đăng Nhập để sử dụng chức năng");
        }
    }//GEN-LAST:event_JPnCPassMouseClicked

    private void LogoutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LogoutKeyPressed
        // TODO add your handling code here:      
    }//GEN-LAST:event_LogoutKeyPressed

    private void JPnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnLogoutMouseEntered
        // TODO add your handling code here:
         JPnLogout.setBackground(colorReChuot);
    }//GEN-LAST:event_JPnLogoutMouseEntered

    private void JPnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnLogoutMouseExited
        // TODO add your handling code here:
        JPnLogout.setBackground(colorMacDinh);
    }//GEN-LAST:event_JPnLogoutMouseExited

    private void JPnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnLogoutMouseClicked
        // TODO add your handling code here:
        JPnLogout.setBackground(colorClick);
        admin.user = null;
        setPanel(new DangNhap());
    }//GEN-LAST:event_JPnLogoutMouseClicked

    private void jLabel5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel5KeyPressed
        // TODO add your handling code here:bo
    }//GEN-LAST:event_jLabel5KeyPressed

    private void JPnBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnBanHangMouseClicked
        // TODO add your handling code here:
if (admin.isLogin()) {
        JPnBanHang.setBackground(colorClick);
        setPanel(new BanHangJPanel());
        }else{
            Message.alert(this, "Đăng Nhập để sử dụng chức năng");
        }
    }//GEN-LAST:event_JPnBanHangMouseClicked

    private void JPnBanHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnBanHangMouseEntered
        // TODO add your handling code here:
         JPnBanHang.setBackground(colorReChuot);
    }//GEN-LAST:event_JPnBanHangMouseEntered

    private void JPnBanHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnBanHangMouseExited
        // TODO add your handling code here:
         JPnBanHang.setBackground(colorMacDinh);
    }//GEN-LAST:event_JPnBanHangMouseExited

    private void jLabel6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel6KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6KeyPressed

    private void JPnHangHoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnHangHoaMouseClicked
        // TODO add your handling code here:
         JPnHangHoa.setBackground(colorClick);
         setPanel(new HangHoaJPanel());
         
    }//GEN-LAST:event_JPnHangHoaMouseClicked

    private void JPnHangHoaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnHangHoaMouseEntered
        // TODO add your handling code here:
         JPnHangHoa.setBackground(colorReChuot);
    }//GEN-LAST:event_JPnHangHoaMouseEntered

    private void JPnHangHoaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnHangHoaMouseExited
        // TODO add your handling code here:
         JPnHangHoa.setBackground(colorMacDinh);
    }//GEN-LAST:event_JPnHangHoaMouseExited

    private void jLabel7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel7KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7KeyPressed

    private void JPnKhoHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnKhoHangMouseClicked
        // TODO add your handling code here:
         JPnKhoHang.setBackground(colorClick);
         setPanel(new KhoHangJPanel());
    }//GEN-LAST:event_JPnKhoHangMouseClicked

    private void JPnKhoHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnKhoHangMouseEntered
        // TODO add your handling code here:
        JPnKhoHang.setBackground(colorReChuot);
    }//GEN-LAST:event_JPnKhoHangMouseEntered

    private void JPnKhoHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnKhoHangMouseExited
        // TODO add your handling code here:
        JPnKhoHang.setBackground(colorMacDinh);
    }//GEN-LAST:event_JPnKhoHangMouseExited

    private void jLabel8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel8KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8KeyPressed

    private void JPnPhieuChiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnPhieuChiMouseClicked
        // TODO add your handling code here:
        JPnPhieuChi.setBackground(colorClick);
        setPanel(new PhieuChiJPanel());
    }//GEN-LAST:event_JPnPhieuChiMouseClicked

    private void JPnPhieuChiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnPhieuChiMouseEntered
        // TODO add your handling code here:
        JPnPhieuChi.setBackground(colorReChuot);
    }//GEN-LAST:event_JPnPhieuChiMouseEntered

    private void JPnPhieuChiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnPhieuChiMouseExited
        // TODO add your handling code here:
        JPnPhieuChi.setBackground(colorMacDinh);
    }//GEN-LAST:event_JPnPhieuChiMouseExited

    private void jLabel10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel10KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10KeyPressed

    private void JPnQuanLyKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnQuanLyKhachHangMouseClicked
        // TODO add your handling code here:
        JPnQuanLyKhachHang.setBackground(colorClick);
        setPanel(new QLKhachHangJPanel());
    }//GEN-LAST:event_JPnQuanLyKhachHangMouseClicked

    private void JPnQuanLyKhachHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnQuanLyKhachHangMouseEntered
        // TODO add your handling code here:
        JPnQuanLyKhachHang.setBackground(colorReChuot);
    }//GEN-LAST:event_JPnQuanLyKhachHangMouseEntered

    private void JPnQuanLyKhachHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnQuanLyKhachHangMouseExited
        // TODO add your handling code here:
        JPnQuanLyKhachHang.setBackground(colorMacDinh);
    }//GEN-LAST:event_JPnQuanLyKhachHangMouseExited

    private void jLabel11KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel11KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11KeyPressed

    private void JPnQuanLyLuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnQuanLyLuongMouseClicked
        // TODO add your handling code here:
        JPnQuanLyLuong.setBackground(colorClick);
        setPanel(new QLLuongJPanel());
    }//GEN-LAST:event_JPnQuanLyLuongMouseClicked

    private void JPnQuanLyLuongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnQuanLyLuongMouseEntered
        // TODO add your handling code here:
         JPnQuanLyLuong.setBackground(colorReChuot);
    }//GEN-LAST:event_JPnQuanLyLuongMouseEntered

    private void JPnQuanLyLuongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnQuanLyLuongMouseExited
        // TODO add your handling code here:
         JPnQuanLyLuong.setBackground(colorMacDinh);
    }//GEN-LAST:event_JPnQuanLyLuongMouseExited

    private void jLabel12KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel12KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12KeyPressed

    private void JPnQuanLyNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnQuanLyNhanVienMouseClicked
        // TODO add your handling code here:
        if (admin.isManager()) {
       JPnQuanLyNhanVien.setBackground(colorClick);
         setPanel(new QLNhanVienJPanel());
        }else{
            Message.alert(this, "Chỉ Quản lý được sử dụng chức năng này");
        }

    }//GEN-LAST:event_JPnQuanLyNhanVienMouseClicked

    private void JPnQuanLyNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnQuanLyNhanVienMouseEntered
        // TODO add your handling code here:
         JPnQuanLyNhanVien.setBackground(colorReChuot);
    }//GEN-LAST:event_JPnQuanLyNhanVienMouseEntered

    private void JPnQuanLyNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnQuanLyNhanVienMouseExited
        // TODO add your handling code here:
         JPnQuanLyNhanVien.setBackground(colorMacDinh);
    }//GEN-LAST:event_JPnQuanLyNhanVienMouseExited

    private void jLabel13KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel13KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13KeyPressed

    private void JPnThongKeDoanhThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnThongKeDoanhThuMouseClicked
        // TODO add your handling code here:
         JPnThongKeDoanhThu.setBackground(colorClick);
         setPanel(new ThongKeDoanhThuJPanel());
    }//GEN-LAST:event_JPnThongKeDoanhThuMouseClicked

    private void JPnThongKeDoanhThuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnThongKeDoanhThuMouseEntered
        // TODO add your handling code here:
        JPnThongKeDoanhThu.setBackground(colorReChuot);
    }//GEN-LAST:event_JPnThongKeDoanhThuMouseEntered

    private void JPnThongKeDoanhThuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnThongKeDoanhThuMouseExited
        // TODO add your handling code here:
        JPnThongKeDoanhThu.setBackground(colorMacDinh);
    }//GEN-LAST:event_JPnThongKeDoanhThuMouseExited

    private void jLabel14KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel14KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14KeyPressed

    private void JPnThongKeLuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnThongKeLuongMouseClicked
        // TODO add your handling code here:
        JPnThongKeLuong.setBackground(colorClick);
        setPanel(new ThongKeLuongJPanel());
    }//GEN-LAST:event_JPnThongKeLuongMouseClicked

    private void JPnThongKeLuongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnThongKeLuongMouseEntered
        // TODO add your handling code here:
        JPnThongKeLuong.setBackground(colorReChuot);
    }//GEN-LAST:event_JPnThongKeLuongMouseEntered

    private void JPnThongKeLuongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnThongKeLuongMouseExited
        // TODO add your handling code here:
        JPnThongKeLuong.setBackground(colorMacDinh);
    }//GEN-LAST:event_JPnThongKeLuongMouseExited

    private void jLabel15KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel15KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15KeyPressed

    private void JPnLichSuGiaoDichMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnLichSuGiaoDichMouseClicked
        // TODO add your handling code here:
        JPnLichSuGiaoDich.setBackground(colorClick);
        setPanel(new LSGDJPanel());
    }//GEN-LAST:event_JPnLichSuGiaoDichMouseClicked

    private void JPnLichSuGiaoDichMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnLichSuGiaoDichMouseEntered
        // TODO add your handling code here:
        JPnLichSuGiaoDich.setBackground(colorReChuot);
    }//GEN-LAST:event_JPnLichSuGiaoDichMouseEntered

    private void JPnLichSuGiaoDichMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnLichSuGiaoDichMouseExited
        // TODO add your handling code here:
        JPnLichSuGiaoDich.setBackground(colorMacDinh);
    }//GEN-LAST:event_JPnLichSuGiaoDichMouseExited

    private void jLabel16KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel16KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16KeyPressed

    private void JPnChamCongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnChamCongMouseClicked
        // TODO add your handling code here:
        JPnChamCong.setBackground(colorClick);
        setPanel(new ChamCongJPanel());
    }//GEN-LAST:event_JPnChamCongMouseClicked

    private void JPnChamCongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnChamCongMouseEntered
        // TODO add your handling code here:
         JPnChamCong.setBackground(colorReChuot);
    }//GEN-LAST:event_JPnChamCongMouseEntered

    private void JPnChamCongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnChamCongMouseExited
        // TODO add your handling code here:
         JPnChamCong.setBackground(colorMacDinh);
    }//GEN-LAST:event_JPnChamCongMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        HuyHoaDon();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // TODO add your handling code here:
                JPnQuanLyKhachHang.setBackground(colorClick);
        setPanel(new DangNhap());
    }//GEN-LAST:event_LogoutMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setPanel(new GiamGiaPanel());
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainQuanLyQuanCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainQuanLyQuanCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainQuanLyQuanCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainQuanLyQuanCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainQuanLyQuanCafe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPnAcc;
    private javax.swing.JPanel JPnBanHang;
    private javax.swing.JPanel JPnCPass;
    private javax.swing.JPanel JPnChamCong;
    private javax.swing.JPanel JPnHangHoa;
    private javax.swing.JPanel JPnKhoHang;
    private javax.swing.JPanel JPnLichSuGiaoDich;
    private javax.swing.JPanel JPnLogo;
    private javax.swing.JPanel JPnLogout;
    private javax.swing.JPanel JPnMainView;
    private javax.swing.JPanel JPnMenu;
    private javax.swing.JPanel JPnPhieuChi;
    private javax.swing.JPanel JPnQuanLyKhachHang;
    private javax.swing.JPanel JPnQuanLyLuong;
    private javax.swing.JPanel JPnQuanLyNhanVien;
    private javax.swing.JPanel JPnThongKeDoanhThu;
    private javax.swing.JPanel JPnThongKeLuong;
    private javax.swing.JLabel Logout;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tblDichVu;
    private javax.swing.JLabel tblLogo;
    private javax.swing.JLabel tblTenNV;
    private javax.swing.JLabel tblThongtin;
    // End of variables declaration//GEN-END:variables
    
    void init(){ 
         this.setLocationRelativeTo(null);
         new DangNhapDialog(this, true).setVisible(true);
         if(admin.isLogin()){
         tblTenNV.setText(admin.user.getTennv());
         } 
    }
    void HuyHoaDon() {
        if(BanHangSP.CheckMaBanHang()){
            HoaDonBanHangDAO hdbhdao = new HoaDonBanHangDAO();
        if(Message.confirm(this,"Bạn chắc chắn hủy hóa đơn bên trên chứ ? ")){
        hdbhdao.delete(BanHangSP.getMaHoaDonBanHang());
        BanHangSP.resetMaBanHang();
        this.setVisible(false);
    }else{
           Message.alert(this,"Hủy hóa đơn Thất bại");
        }
    }
        System.exit(0);
    }
   
}
